name: yes_play_music
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0+1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.1
  logger: ^2.0.2
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  qr_flutter: ^4.1.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/

flutter_assets:
  assets_path: lib/assets/images/
  output_path: lib/assets/imageCode/